-- Q1. How many total orders do we have?


-- SELECT COUNT(*) AS Total_Orders
-- FROM Supply_Chain;
-- Q2. What is the total revenue?


-- SELECT SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain; 


-- -- Q3. What is the average order value?-- 
-- SELECT AVG(Revenue) AS Average_Order_Value
-- FROM Supply_Chain;

-- -- Q4. What is the total quantity sold?
-- SELECT SUM(Quantity) AS Total_Quantity_Sold
-- FROM Supply_Chain;

-- -- Q5. What is the average delivery time?

-- SELECT AVG(Delivery_Days) AS Average_Delivery_Days
-- FROM Supply_Chain;


-- -- Q6. How much revenue does each category generate?
-- SELECT
--     Category,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Category;

-- -- Q7. How many orders are in each category?
-- SELECT
--     Category,
--     COUNT(*) AS Total_Orders
-- FROM Supply_Chain
-- GROUP BY Category;

-- -- Q8. What is the average order value by category?
-- SELECT
--     Category,
--     AVG(Revenue) AS Average_Order_Value
-- FROM Supply_Chain
-- GROUP BY Category;


-- -- Q9. Which categories generated more than ₹5,00,000 revenue?

-- SELECT
--     Category,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Category
-- HAVING SUM(Revenue) > 500000;

-- -- Q10. How many orders came from each region?
-- SELECT
--     Region,
--     COUNT(*) AS Total_Orders
-- FROM Supply_Chain
-- GROUP BY Region;


-- -- Q11. What is the revenue generated by each region?
-- SELECT
--     Region,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Region;

-- -- Q12. Which region generated the highest revenue?


-- SELECT
--     Region,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Region
-- ORDER BY Total_Revenue DESC
-- LIMIT 1;


-- -- Q13. Which regions have an average delivery time greater than 4 days?
-- SELECT
--     Region,
--     AVG(Delivery_Days) AS Avg_Delivery_Days
-- FROM Supply_Chain
-- GROUP BY Region
-- HAVING AVG(Delivery_Days) > 4;


-- -- Q14. How many orders does each warehouse handle?
-- SELECT
--     Warehouse,
--     COUNT(*) AS Total_Orders
-- FROM Supply_Chain
-- GROUP BY Warehouse;


-- -- Q15. How many delayed orders does each warehouse have?
-- SELECT
--     Warehouse,
--     COUNT(*) AS Delayed_Orders
-- FROM Supply_Chain
-- WHERE Delivery_Status = 'Delayed'
-- GROUP BY Warehouse;


-- -- Q16. What is the average delivery time for each warehouse?
-- SELECT
--     Warehouse,
--     AVG(Delivery_Days) AS Avg_Delivery_Days
-- FROM Supply_Chain
-- GROUP BY Warehouse;


-- -- . Which warehouses have more than 10 delayed orders?
-- SELECT
--     Warehouse,
--     COUNT(*) AS Delayed_Orders
-- FROM Supply_Chain
-- WHERE Delivery_Status = 'Delayed'
-- GROUP BY Warehouse
-- HAVING COUNT(*) > 10;

-- -- Q18. Categorize orders as Fast, Normal, or Slow.

-- -- Business rule:

-- -- 1–3 days → Fast
-- -- 4–5 days → Normal
-- -- 6+ days → Slow
-- SELECT
--     Order_ID,
--     Delivery_Days,
--     CASE
--         WHEN Delivery_Days BETWEEN 1 AND 3 THEN 'Fast'
--         WHEN Delivery_Days BETWEEN 4 AND 5 THEN 'Normal'
--         ELSE 'Slow'
--     END AS Delivery_Category
-- FROM Supply_Chain;



-- -- Q19. How many Fast, Normal, and Slow orders are there?
-- SELECT
--     CASE
--         WHEN Delivery_Days BETWEEN 1 AND 3 THEN 'Fast'
--         WHEN Delivery_Days BETWEEN 4 AND 5 THEN 'Normal'
--         ELSE 'Slow'
--     END AS Delivery_Category,
--     COUNT(*) AS Total_Orders
-- FROM Supply_Chain
-- GROUP BY
--     CASE
--         WHEN Delivery_Days BETWEEN 1 AND 3 THEN 'Fast'
--         WHEN Delivery_Days BETWEEN 4 AND 5 THEN 'Normal'
--         ELSE 'Slow'
--     END;


-- Q20. How many orders were On-Time vs Delayed?
-- SELECT
--     Delivery_Status,
--     COUNT(*) AS Total_Orders
-- FROM Supply_Chain
-- GROUP BY Delivery_Status;


-- Q21. What percentage of orders were delivered on time?
-- SELECT
--     ROUND(
--         SUM(CASE WHEN Delivery_Status = 'On-Time' THEN 1 ELSE 0 END)
--         * 100.0 / COUNT(*),
--         2
--     ) AS On_Time_Percentage
-- FROM Supply_Chain;


-- -- Q22. Which products generate the most revenue?
-- SELECT
--     Product,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Product
-- ORDER BY Total_Revenue DESC;



-- -- Q24. Which customers generated the most revenue?
-- SELECT
--     Customer,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Customer
-- ORDER BY Total_Revenue DESC;




-- -- Which category has the highest average order value?

-- SELECT
--     Category,
--     AVG(Revenue) AS Average_Order_Value
-- FROM Supply_Chain
-- GROUP BY Category
-- ORDER BY Average_Order_Value DESC
-- LIMIT 1;

-- -- Which warehouse has the highest revenue?

-- SELECT
--     Warehouse,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Warehouse
-- ORDER BY Total_Revenue DESC
-- LIMIT 1;


-- -- Which regions have more than 20 orders and revenue greater than ₹5,00,000?

-- SELECT
--     Region,
--     COUNT(*) AS Total_Orders,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Region
-- HAVING COUNT(*) > 20
--    AND SUM(Revenue) > 500000;

-- -- Which regions have more than 20 orders and revenue greater than ₹5,00,000?

-- SELECT
--     Region,
--     COUNT(*) AS Total_Orders,
--     SUM(Revenue) AS Total_Revenue
-- FROM Supply_Chain
-- GROUP BY Region
-- HAVING COUNT(*) > 20
--    AND SUM(Revenue) > 500000;







-- use warehouse_info;-- -- 

-- INSERT INTO Warehouse_Info
-- (Warehouse, City, Manager_Name)
-- VALUES
-- ('WH-A','Delhi','Rakesh'),
-- ('WH-B','Mumbai','Priya'),
-- ('WH-C','Bangalore','Amit');

-- Show warehouse, city, manager, total orders, total revenue, and average delivery days.



SELECT
    w.Warehouse,
    w.City,
    w.Manager_Name,
    COUNT(s.Order_ID) AS Total_Orders,
    SUM(s.Revenue) AS Total_Revenue,
    AVG(s.Delivery_Days) AS Avg_Delivery_Days
FROM Warehouse_Info w
LEFT JOIN Supply_Chain s
    ON w.Warehouse = s.Warehouse
GROUP BY
    w.Warehouse,
    w.City,
    w.Manager_Name;
    
    










